hadoop-mysql:
   image: tonywell/docker-mysql
   container_name: hadoop-mysql
   volumes:
     - ./data:/usr/local/mysql-5.7.33-linux-glibc2.12-x86_64/data
   net: zoo
   command: /usr/local/mysql-5.7.33-linux-glibc2.12-x86_64/bin/mysqld_safe --user=mysql
   ports: 
     - "3306:3306"
